## Import Modules

In [2]:
import pandas as pd
import altair as alt

## Clean data

In [3]:
url = "https://www.espn.com/nba/player/gamelog/_/id/3112335/nikola-jokic"
df = pd.read_html(url)
jan = df[1].drop(columns=["Date","OPP","Result"])

jan = jan.drop(3).drop(17)
jan

   MIN     FG   FG%  3PT    3P%     FT    FT% REB AST BLK STL PF TO PTS
0   28    7-9  77.8  2-4   50.0    2-2  100.0  10  15   1   3  1  5  18
1   30  11-19  57.9  3-6   50.0    4-4  100.0  13  10   0   2  5  6  29
2   35   8-13  61.5  2-2  100.0    8-8  100.0  10   8   0   1  5  2  26
4   34   9-20  45.0  3-8   37.5    7-7  100.0  21   9   0   1  2  3  28
5   36  12-19  63.2  1-6   16.7   9-10   90.0   9   8   1   2  1  3  34
6   40  11-16  68.8  2-4   50.0    2-3   66.7  11  12   1   2  3  0  26
7   41  16-25  64.0  3-5   60.0  14-16   87.5  14  10   1   3  4  5  49
8   37  10-18  55.6  2-5   40.0    3-3  100.0  15  14   0   2  5  3  25
9   28   7-12  58.3  1-2   50.0    2-2  100.0  12  13   0   1  1  3  17
10  28   8-10  80.0  1-2   50.0    3-3  100.0   8   7   2   0  2  3  20
11  37   9-14  64.3  1-3   33.3    2-2  100.0  13   8   0   1  2  5  21
12  33   8-21  38.1  1-3   33.3    5-5  100.0  18   6   0   1  0  2  22
13  34  13-20  65.0  3-6   50.0    4-8   50.0  10   7   2   2  3  2  33
14  37  10-17  58.8  1-3   33.3    5-6   83.3  21  11   2   0  2  5  26
15  35  11-18  61.1  1-4   25.0    4-4  100.0  16   3   0   2  3  3  27
16  25   8-12  66.7  1-2   50.0    7-9   77.8  11   3   1   0  4  4  24

In [4]:
feb = df[0].drop(columns=["Date","OPP","Result"])

feb = feb.drop(7)
feb

,MIN,FG,FG%,3PT,3P%,FT,FT%,REB,AST,BLK,STL,PF,TO,PTS
0,34.0,13-24,54.2,3-5,60.0,6-9,66.7,17.0,8.0,1.0,0.0,3.0,5.0,35.0
1,35.0,10-26,38.5,3-9,33.3,3-3,100.0,15.0,7.0,0.0,1.0,2.0,5.0,26.0
2,35.0,10-16,62.5,0-2,0.0,8-10,80.0,15.0,6.0,2.0,0.0,1.0,4.0,28.0
3,34.0,9-20,45.0,3-10,30.0,2-4,50.0,16.0,11.0,2.0,0.0,2.0,9.0,23.0
4,30.0,8-14,57.1,0-3,0.0,5-7,71.4,11.0,7.0,0.0,0.0,2.0,6.0,21.0
5,30.0,12-15,80.0,0-2,0.0,3-4,75.0,12.0,10.0,1.0,2.0,1.0,2.0,27.0
6,35.0,7-10,70.0,3-3,100.0,8-8,100.0,12.0,9.0,0.0,2.0,4.0,4.0,25.0
8,33.0,9.4-17.1,54.7,1.6-4.8,34.2,5.4-6.8,79.6,14.3,8.3,0.6,0.9,2.3,5.0,25.8

In [5]:
this_year = pd.concat([jan,feb])
this_year = this_year.reset_index().drop(columns=['index'])
this_year = this_year.rename(columns={"3P%":"Three_Percentage","3PT":"Three_PT","FG%":"FG_Percentage"})

In [6]:
a = this_year.drop(columns=['FG','Three_PT','FT']).astype(float)
a

,MIN,FG_Percentage,Three_Percentage,FT%,REB,AST,BLK,STL,PF,TO,PTS
0,28.0,77.8,50.0,100.0,10.0,15.0,1.0,3.0,1.0,5.0,18.0
1,30.0,57.9,50.0,100.0,13.0,10.0,0.0,2.0,5.0,6.0,29.0
2,35.0,61.5,100.0,100.0,10.0,8.0,0.0,1.0,5.0,2.0,26.0
3,34.0,45.0,37.5,100.0,21.0,9.0,0.0,1.0,2.0,3.0,28.0
4,36.0,63.2,16.7,90.0,9.0,8.0,1.0,2.0,1.0,3.0,34.0
5,40.0,68.8,50.0,66.7,11.0,12.0,1.0,2.0,3.0,0.0,26.0
6,41.0,64.0,60.0,87.5,14.0,10.0,1.0,3.0,4.0,5.0,49.0
7,37.0,55.6,40.0,100.0,15.0,14.0,0.0,2.0,5.0,3.0,25.0
8,28.0,58.3,50.0,100.0,12.0,13.0,0.0,1.0,1.0,3.0,17.0
9,28.0,80.0,50.0,100.0,8.0,7.0,2.0,0.0,2.0,3.0,20.0
10,37.0,64.3,33.3,100.0,13.0,8.0,0.0,1.0,2.0,5.0,21.0
11,33.0,38.1,33.3,100.0,18.0,6.0,0.0,1.0,0.0,2.0,22.0
12,34.0,65.0,50.0,50.0,10.0,7.0,2.0,2.0,3.0,2.0,33.0
13,37.0,58.8,33.3,83.3,21.0,11.0,2.0,0.0,2.0,5.0,26.0
14,35.0,61.1,25.0,100.0,16.0,3.0,0.0,2.0,3.0,3.0,27.0
15,25.0,66.7,50.0,77.8,11.0,3.0,1.0,0.0,4.0,4.0,24.0
16,34.0,54.2,60.0,66.7,17.0,8.0,1.0,0.0,3.0,5.0,35.0
17,35.0,38.5,33.3,100.0,15.0,7.0,0.0,1.0,2.0,5.0,26.0
18,35.0,62.5,0.0,80.0,15.0,6.0,2.0,0.0,1.0,4.0,28.0
19,34.0,45.0,30.0,50.0,16.0,11.0,2.0,0.0,2.0,9.0,23.0
20,30.0,57.1,0.0,71.4,11.0,7.0,0.0,0.0,2.0,6.0,21.0
21,30.0,80.0,0.0,75.0,12.0,10.0,1.0,2.0,1.0,2.0,27.0
22,35.0,70.0,100.0,100.0,12.0,9.0,0.0,2.0,4.0,4.0,25.0
23,33.0,54.7,34.2,79.6,14.3,8.3,0.6,0.9,2.3,5.0,25.8

Question1: Will his FG% drop if he plays longer time?

In [7]:

alt.Chart(a).mark_circle().encode(
    x=alt.X('MIN'),
    y=alt.Y('FG_Percentage')
)

alt.Chart(...)

According to the chart I made, we can see playing for a longer time does not make his percentage drop.

Answer1: He can play consistently.

## Make strings to float

In [8]:
df1 =(this_year.FG
    .str.split('-',expand=True)
    .rename(columns = {0: 'Make', 1: 'Shoot'})
    .astype(float))

df1

    Make  Shoot
0    7.0    9.0
1   11.0   19.0
2    8.0   13.0
3    9.0   20.0
4   12.0   19.0
5   11.0   16.0
6   16.0   25.0
7   10.0   18.0
8    7.0   12.0
9    8.0   10.0
10   9.0   14.0
11   8.0   21.0
12  13.0   20.0
13  10.0   17.0
14  11.0   18.0
15   8.0   12.0
16  13.0   24.0
17  10.0   26.0
18  10.0   16.0
19   9.0   20.0
20   8.0   14.0
21  12.0   15.0
22   7.0   10.0
23   9.4   17.1

In [9]:
df2 = (this_year.FT
    .str.split('-',expand=True)
    .rename(columns = {0: 'FT_Make', 1: 'FT_Shoot'})
    .astype(float))

df2

    FT_Make  FT_Shoot
0       2.0       2.0
1       4.0       4.0
2       8.0       8.0
3       7.0       7.0
4       9.0      10.0
5       2.0       3.0
6      14.0      16.0
7       3.0       3.0
8       2.0       2.0
9       3.0       3.0
10      2.0       2.0
11      5.0       5.0
12      4.0       8.0
13      5.0       6.0
14      4.0       4.0
15      7.0       9.0
16      6.0       9.0
17      3.0       3.0
18      8.0      10.0
19      2.0       4.0
20      5.0       7.0
21      3.0       4.0
22      8.0       8.0
23      5.4       6.8

In [10]:
df3 = (this_year.Three_PT
    .str.split('-',expand=True)
    .rename(columns = {0: 'Three_Make', 1: 'Three_Shoot'})
    .astype(float))

df3

    Three_Make  Three_Shoot
0          2.0          4.0
1          3.0          6.0
2          2.0          2.0
3          3.0          8.0
4          1.0          6.0
5          2.0          4.0
6          3.0          5.0
7          2.0          5.0
8          1.0          2.0
9          1.0          2.0
10         1.0          3.0
11         1.0          3.0
12         3.0          6.0
13         1.0          3.0
14         1.0          4.0
15         1.0          2.0
16         3.0          5.0
17         3.0          9.0
18         0.0          2.0
19         3.0         10.0
20         0.0          3.0
21         0.0          2.0
22         3.0          3.0
23         1.6          4.8

In [11]:
re = pd.concat([df1,df2,df3],axis=1)
re

    Make  Shoot  FT_Make  FT_Shoot  Three_Make  Three_Shoot
0    7.0    9.0      2.0       2.0         2.0          4.0
1   11.0   19.0      4.0       4.0         3.0          6.0
2    8.0   13.0      8.0       8.0         2.0          2.0
3    9.0   20.0      7.0       7.0         3.0          8.0
4   12.0   19.0      9.0      10.0         1.0          6.0
5   11.0   16.0      2.0       3.0         2.0          4.0
6   16.0   25.0     14.0      16.0         3.0          5.0
7   10.0   18.0      3.0       3.0         2.0          5.0
8    7.0   12.0      2.0       2.0         1.0          2.0
9    8.0   10.0      3.0       3.0         1.0          2.0
10   9.0   14.0      2.0       2.0         1.0          3.0
11   8.0   21.0      5.0       5.0         1.0          3.0
12  13.0   20.0      4.0       8.0         3.0          6.0
13  10.0   17.0      5.0       6.0         1.0          3.0
14  11.0   18.0      4.0       4.0         1.0          4.0
15   8.0   12.0      7.0       9.0         1.0          2.0
16  13.0   24.0      6.0       9.0         3.0          5.0
17  10.0   26.0      3.0       3.0         3.0          9.0
18  10.0   16.0      8.0      10.0         0.0          2.0
19   9.0   20.0      2.0       4.0         3.0         10.0
20   8.0   14.0      5.0       7.0         0.0          3.0
21  12.0   15.0      3.0       4.0         0.0          2.0
22   7.0   10.0      8.0       8.0         3.0          3.0
23   9.4   17.1      5.4       6.8         1.6          4.8

In [12]:
re.mean()

Make            9.850000
Shoot          16.879167
FT_Make         5.058333
FT_Shoot        5.991667
Three_Make      1.733333
Three_Shoot     4.325000
dtype: float64

## Comparison

In this part, I will filter the table when the field goal percentage is greater than 50% and less than 50%.

In [13]:
# When he shoot greater than 50% 
a.query("FG_Percentage >= 50").mean()

MIN                 33.400
FG_Percentage       64.075
Three_Percentage    42.625
FT%                 86.400
REB                 12.715
AST                  8.865
BLK                  0.780
STL                  1.295
PF                   2.715
TO                   3.750
PTS                 26.840
dtype: float64

In [17]:
# When he shoot less than 50% 
a.query("FG_Percentage < 50").mean()

MIN                 34.000
FG_Percentage       41.650
Three_Percentage    33.525
FT%                 87.500
REB                 17.500
AST                  8.250
BLK                  0.500
STL                  0.750
PF                   1.500
TO                   4.750
PTS                 24.750
dtype: float64

Answer: When he is not good at shooting, he will get more rebounds. When he does not shoot well, we still do not need to worry about him.